### ALIAS ###
alias lsl='ls -lh'
alias aar='sudo apt autoremove -y'
alias adga='adg -y && aar'
alias rstart='screen -dmS rtorrent rtorrent'
alias rt='stty stop undef; stty start undef; screen -x rtorrent'
alias tsd='tmux new-session -d -s'
alias aii='$HOME/.aii.sh'
alias vu='globalprotect connect'
alias vd='globalprotect disconnect'
alias vs='globalprotect show --status'
alias reload='exec zsh'
alias py='python3'
### ALIAS ###

### SSH ALIAS ###
alias home1='ssh home1'
alias home1-fs='temp_server=home1; temp_path=/home/smc; [ ! -d ~/mnt/$temp_server ] && mkdir -p ~/mnt/$temp_server; sshfs $temp_server:$temp_path ~/mnt/$temp_server'
alias home2='ssh home2'
alias home1l='ssh home1l'
alias home2l='ssh home2l'
alias seedbox='ssh seedbox'
alias deepv='ssh deepv'
alias gaivi='ssh gaivi'
alias gaivi2='ssh gaivi2'
alias carrt='ssh carrt'
alias puppy='ssh puppy'
alias beast='ssh beast'
alias beast-fs='temp_server=beast; temp_path=/home/smc; [ ! -d ~/mnt/$temp_server ] && mkdir -p ~/mnt/$temp_server; sshfs $temp_server:$temp_path ~/mnt/$temp_server'
alias beast-um='umount ~/mnt/beast'
alias hulk='ssh hulk'
alias hulk-fs='temp_server=hulk; temp_path=/home/smc; [ ! -d ~/mnt/$temp_server ] && mkdir -p ~/mnt/$temp_server; sshfs $temp_server:$temp_path ~/mnt/$temp_server'
alias hulk-um='umount ~/mnt/hulk'
### SSH ALIAS ###